# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "05:00"
    open-pull-requests-limit: 2
    versioning-strategy: increase
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "05:00"
    open-pull-requests-limit: 2
    rebase-strategy: "disabled"
