= New Bonita Documentation Site
// External URIs:
:url-antora: https://antora.org
:url-asciidoctor: https://asciidoctor.org/
:url-node: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation


*_DISCLAIMER: this is a work in progress._*


== Architecture

Static site generation based on {url-antora}:[Antora] using {url-asciidoctor}:[Asciidoctor] documentation content stored in various Git repositories.


== Build

=== Requirements


{url-node}:[Node 12.x] (may work with newer versions, no guarantee). For more details, see the  https://docs.antora.org/antora/2.3/install-and-run-quickstart/[Antora installation guide].

While you can install Node from the official packages, we strongly recommend that you use {url-nvm}[nvm] (Node Version Manager) to install and manage Node.
Follow the {url-nvm-install}[nvm installation instructions] to set up nvm on your machine.

=== Build the static site

Run
```bash
npm install
npm run build
```
The static site is then available in the `build` folder.


The `antora` CLI is available by calling `./node_modules/.bin/antora --version`
