name: 'Comments PR with useful links'
description: 'Add a comment to help reviewer on a PR'

inputs:
  site-url:
    description: 'The url of preview to check the PR update'
    required: true
  component-name:
    description: 'The name of the component to build. If set, the build-preview-command input is ignored'
    required: false
    default: 'bonita'
  pattern:
    description: ''
    required: false
    default: 'modules/**/*.adoc'
  # needed by content repository (default master) and here (computed automagically)
  doc-site-branch:
    description: 'The branch of the `bonita-documentation-site` used to download js files'
    required: false
    default: 'master'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changed files in PR
      id: changed-files
      continue-on-error: true # we will verify the error in a later step
      uses: tj-actions/changed-files@v35
      with:
        files: |
          ${{inputs.pattern}}
    - name: Check result
      id: get-changed-files
      uses: actions/github-script@v6
      env:
        DETECTION_STATUS: ${{steps.changed-files.outcome}}
      with:
        script: |
          const {DETECTION_STATUS} = process.env;
          core.info(`Outcome of the 'get-changed-files' step is: ${DETECTION_STATUS}`);
          if(DETECTION_STATUS === 'failure') {
            return 'false';
          }
          return 'true';
    - name: Log files changed
      if: ${{steps.get-changed-files.outputs.result == 'true' }}
      shell: bash
      run: |
        echo "${{ steps.changed-files.outputs.all_changed_files }}"
    - name: Checkout
      uses: actions/checkout@v3
      if: ${{ github.event.action != 'closed' }}
      with:
        repository: 'bonitasoft/bonita-documentation-site'
        ref: ${{ inputs.doc-site-branch }}
        path: bds
    - name: Compute links to display
      uses: actions/github-script@v6
      if: ${{steps.get-changed-files.outputs.result == 'true' }}
      id: set-result
      env:
        FILES: ${{steps.changed-files.outputs.all_changed_files}}
        DELETED: ${{steps.changed-files.outputs.deleted_files}}
        SITE_URL: ${{ inputs.site-url }}
        COMPONENT_NAME: ${{ inputs.component-name }}
      with:
        script: |
          const script = require('./bds/.github/actions/comment-pr-with-links/comments-with-url-links.js');
          return await script.prepareUrlLinks({github, context});
    - name: Create or update comments
      if: ${{steps.get-changed-files.outputs.result == 'true' }}
      uses: actions/github-script@v6
      env:
        LINKS: ${{steps.set-result.outputs.result}}
        HAS_DELETED_FILES: ${{steps.changed-files.outputs.any_deleted}}
      with:
        script: |
          const script = require('./bds/.github/actions/comment-pr-with-links/comments-with-url-links.js');
          return await script.createOrUpdateComments({github, context});
        result-encoding: string
