name: 'Validate the PR branch name'
description: 'Ensure that the branch match a pattern that works with Antora'

runs:
  using: "composite"
  steps:
    - name: Validate branch name
      uses: actions/github-script@v7
      with:
        script: |
          const branchName = process.env.GITHUB_HEAD_REF;
          // inspired from https://github.com/goshencollege/validate-branch-name/blob/v1.0.1/index.js
          // only allow backslash, alphanumeric, dot, underscore and dash
          const pattern = '^[\/a-zA-Z0-9._-]+$';
          if (!new RegExp(pattern).test(branchName)) {
            core.setFailed(
              `The branch name ${branchName} does not match the predefined regex pattern: ${pattern}.
              This branch wouldn't be used by Antora to build the preview.
              So there would be missing content and side effects.
              For more details, see https://github.com/bonitasoft/bonita-documentation-site/issues/512.`
            );
          }
