name: 'Build site from PR'
description: 'Build site from a PR to check if all xref references are valid'

inputs:
  build-preview-command:
    description: 'The documentation `build-preview` command to build the preview'
    required: true
  # needed by content repository (default master) and here (computed automagically)
  doc-site-branch:
    description: 'The branch of the `bonita-documentation-site` used to build the site preview'
    required: false
    default: 'master'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: github.event.action != 'closed'
      with:
        repository: 'bonitasoft/bonita-documentation-site'
        ref: ${{ inputs.doc-site-branch }}
    - name: Build Setup
      uses: ./.github/actions/build-setup
      if: github.event.action != 'closed'
    - name: Build Site
      if: github.event.action != 'closed'
      shell: bash
      run: ${{ inputs.build-preview-command }} --fetch-sources true --pr "${{ github.event.pull_request.number }}"
