name: 'Build site from PR'
description: 'Build site from a PR to check if all xref references are valid'

inputs:
  build-preview-command:
    description: 'The documentation `build-preview` command to build the preview'
    required: true
  # needed by content repository (default master) and here (computed automagically)
  doc-site-branch:
    description: 'The branch of the `bonita-documentation-site` used to build the site preview'
    required: false
    default: 'master'
  fail-on-warning:
    description: 'If true, fail the Antora build on warning.'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'bonitasoft/bonita-documentation-site'
        ref: ${{ inputs.doc-site-branch }}
    - name: Validate PR branch name
      uses: ./.github/actions/validate-pr-branch-name
    - name: Build Setup
      uses: ./.github/actions/build-setup
    - name: Install antora dependencies for xref validation
      shell: bash
      run: npm install --save-dev antora@3.2.0-alpha.4
    - name: Build Site
      shell: bash
      # '>' Replace newlines with spaces (folded)
      # '-' No newline at end (strip)
      run: >-
        ${{ inputs.build-preview-command }}
        --fail-on-warning "${{inputs.fail-on-warning}}"
        --fetch-sources true
        --pr "${{ github.event.pull_request.number }}"
    - name: List the content of the generated site
      uses: ./.github/actions/log-built-site-details
    - name: Archive site
      uses: ./.github/actions/upload-pr-built-site-artifact
      with:
        site-type: build
