name: 'Build and publish PR preview on surge.sh'
description: 'Based on the surge-preview, hides the processing logic'

inputs:
  github-token:
    description: 'A token with `pull-requests: write` to let the surge-preview action create comments on pull requests'
    required: true
  surge-token:
    description: 'A surge token to manage the deployment'
    required: true
  build-preview-command:
    description: 'The documentation `build-preview` command to build the preview. Mandatory when `component-name` is not set. Otherwise, ignored.'
    required: false
  # needed by content repository (default master) and here (computed automagically)
  doc-site-branch:
    description: 'The branch of the `bonita-documentation-site` used to build the site preview'
    required: false
    default: 'master'
  component-name:
    description: 'The name of the component to build. If set, the build-preview-command input is ignored'
    required: false
    default: ''
  fail-on-warning:
    description: 'If true, fail the Antora build on warning. Only applies when the `component-name` input is set.'
    required: false
    default: 'false'
  ignore-errors:
    description: 'If `true`, ignores Antora error. Only applies when the `component-name` input is set.'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: github.event.action != 'closed'
      with:
        repository: 'bonitasoft/bonita-documentation-site'
        ref: ${{ inputs.doc-site-branch }}
    - name: Validate PR branch name
      uses: ./.github/actions/validate-pr-branch-name
      if: github.event.action != 'closed'
    - uses: bonitasoft/actions/packages/surge-preview-tools@v2
      id: surge-preview-tools
      with:
        surge-token: ${{ inputs.surge-token }}
    - name: Build Setup
      uses: ./.github/actions/build-setup
      if: github.event.action != 'closed'
    - name: Build Site without error check
      if: github.event.action != 'closed' && inputs.component-name != ''
      shell: bash
      # '>' Replace newlines with spaces (folded)
      # '-' No newline at end (strip)
      run: >-
        ./build-preview.bash
        --branch "${{ github.head_ref }}"
        --component "${{inputs.component-name}}"
        --fail-on-warning "${{inputs.fail-on-warning}}"
        --fetch-sources true
        --ignore-errors "${{inputs.ignore-errors}}"
        --pr "${{ github.event.pull_request.number }}"
        --site-url "${{ steps.surge-preview-tools.outputs.preview-url }}"
    - name: Build Site
      if: github.event.action != 'closed' && inputs.component-name == ''
      shell: bash
      # '>' Replace newlines with spaces (folded)
      # '-' No newline at end (strip)
      run: >-
        ${{ inputs.build-preview-command }}
        --fetch-sources true
        --pr "${{ github.event.pull_request.number }}"
        --site-url "${{ steps.surge-preview-tools.outputs.preview-url }}"
    - name: List the content of the generated site
      if: github.event.action != 'closed'
      uses: ./.github/actions/log-built-site-details
    - name: Publish preview
      uses: afc163/surge-preview@v1
      if: steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
      with:
        surge_token: ${{ inputs.surge-token }}
        github_token: ${{ inputs.github-token }}
        dist: build/site
        failOnError: true
        teardown: true
        build: echo "site already built"
    - name: Archive site preview
      if: github.event.action != 'closed'
      uses: ./.github/actions/upload-pr-built-site-artifact
      with:
        site-type: preview
    - name: Comments PR with useful links
      if: github.event.action != 'closed' && steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
      uses: ./.github/actions/comment-pr-with-links
      with:
        doc-site-branch: ${{ inputs.doc-site-branch }}
        component-name: ${{inputs.component-name}}
        site-url: ${{ steps.surge-preview-tools.outputs.preview-url }}


