name: 'Build and publish PR preview on surge.sh'
description: 'Based on the surge-preview, hides the processing logic'

inputs:
  github-token:
    description: 'A token with `pull-requests: write` to let the surge-preview action create comments on pull requests'
    required: true
  surge-token:
    description: 'A surge token to manage the deployment'
    required: true
  build-preview-command:
    description: 'The documentation `build-preview` command to build the preview'
    required: false
  # needed by content repository (default master) and here (computed automagically)
  doc-site-branch:
    description: 'The branch of the `bonita-documentation-site` used to build the site preview'
    required: false
    default: 'master'
  component-name:
    description: 'The name of the component to build. If set, the build-preview-command input is ignored'
    required: false
    default: ''
  ignore-errors:
    description: 'Only applies when the `component-name` input is set. If `true`, ignores Antora error.'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    # TODO extract in a dedicated action and use it in the build-pr-site action as well
    - name: Validate branch name
      if: github.event.action != 'closed'
      uses: actions/github-script@v6
      with:
        script: |
        // inspired from https://github.com/goshencollege/validate-branch-name/blob/v1.0.1/index.js
        const branchName = github.context.payload.ref.replace("refs/heads/", "");
        // only allow backslash, alphanumeric, dot, underscore and dash
        const pattern = '^[\/a-zA-Z0-9._-]+$';
        if (!nameMatchesPattern(branchName, pattern)) {
          core.setFailed(
            `The branch name ${branchName} does not match the predefined regex pattern - ${pattern}. This branch wouldn't be used by Antora to build the preview.g
            So there would be missing content and side effects.
            For more details, see https://github.com/bonitasoft/bonita-documentation-site/issues/512.`
          );
        }

    - uses: bonitasoft/actions/packages/surge-preview-tools@v2
      id: surge-preview-tools
      with:
        surge-token: ${{ inputs.surge-token }}
    - name: Checkout
      uses: actions/checkout@v3
      if: github.event.action != 'closed'
      with:
        repository: 'bonitasoft/bonita-documentation-site'
        ref: ${{ inputs.doc-site-branch }}
    - name: Build Setup
      uses: ./.github/actions/build-setup
      if: github.event.action != 'closed'
    - name: Build Site without error check
      if: github.event.action != 'closed' && inputs.component-name != ''
      shell: bash
      run: ./build-preview.bash --component "${{inputs.component-name}}" --branch "${{ github.head_ref }}" --ignore-error "${{inputs.ignore-errors}}" --fetch-sources true --pr "${{ github.event.pull_request.number }}" --site-url "${{ steps.surge-preview-tools.outputs.preview-url }}"
    - name: Build Site
      if: github.event.action != 'closed' && inputs.component-name == ''
      shell: bash
      run: ${{ inputs.build-preview-command }} --fetch-sources true --pr "${{ github.event.pull_request.number }}" --site-url "${{ steps.surge-preview-tools.outputs.preview-url }}"
    - name: List the content of the generated site
      if: github.event.action != 'closed'
      uses: ./.github/actions/log-built-site-details
    - name: Publish preview
      uses: afc163/surge-preview@v1
      if: steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
      with:
        surge_token: ${{ inputs.surge-token }}
        github_token: ${{ inputs.github-token }}
        dist: build/site
        failOnError: true
        teardown: true
        build: echo "site already built"
    - name: Archive site preview
      if: github.event.action != 'closed' && steps.surge-preview-tools.outputs.can-run-surge-command != 'true'
      uses: ./.github/actions/upload-pr-built-site-artifact
      with:
        site-type: preview
    - name: Comments PR with useful links
      if: github.event.action != 'closed' && steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
      uses: ./.github/actions/comment-pr-with-links
      with:
        doc-site-branch: ${{ inputs.doc-site-branch }}
        component-name: ${{inputs.component-name}}
        site-url: ${{ steps.surge-preview-tools.outputs.preview-url }}


