name: 'Build Setup'
description: 'Setup node'
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version-file: '.nvmrc'
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
      with:
        # TMP don't ignore scripts to patch the Antora Atlas extension
        # to restore: add ` --ignore-scripts`
        install-command: npm ci --prefer-offline --audit false
