name: 'Build Setup'
description: 'Checkout and setup node'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
