name: 'Check Links Run'
description: 'Runs htmltest and uploads the analysis artifact.'
inputs:
  run-number:
    description: 'The run number (e.g., 01, 02, ...).'
    required: true
  working-directory:
    description: 'Directory to run htmltest in.'
    required: false
    default: 'scripts/htmltest'
  config-file:
    description: 'htmltest config file path.'
    required: false
    default: './htmltest_bonita-documentation-site.yml'
  site-path:
    description: 'Path to the built site.'
    required: false
    default: '../../build/site'
  sleep-before:
    description: 'Whether to sleep before running htmltest.'
    required: false
    default: 'true'
  sleep-seconds:
    description: 'How many seconds to sleep before running htmltest.'
    required: false
    default: '20'
runs:
  using: 'composite'
  steps:
    # Give some time to called website to reset the throttling counters (for example, GitHub returns 429 errors after too many requests in a short time).
    # Subsequent calls should pass.
    - name: Sleep before running htmltest
      if: ${{ inputs.sleep-before == 'true' }}
      uses: softprops/action-sleep@v1
      with:
        time: ${{ inputs.sleep-seconds }}
    - name: Run htmltest
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ./htmltest -c ${{ inputs.config-file }} ${{ inputs.site-path }}
    - name: Upload links analysis
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: check-links-analysis-run_${{ inputs.run-number }}-${{ github.sha }}
        path: ${{ inputs.working-directory }}/config
