= Conversion tips: from markdown to asciidoctor
:icons: font

NOTE: current work used to convert the BICI documentation, see https://github.com/bonitasoft/bonita-ici-doc/pull/118[PR #118]

== Markdown to Asciidoctor generation

=== Tool installation

TIP: Proposed tool Kramdoc aka https://github.com/asciidoctor/kramdown-asciidoc:[kramdown-asciidoc]. See also this https://matthewsetter.com/technical-documentation/asciidoc/convert-markdown-to-asciidoc-with-kramdoc/:[article].


* Require Ruby
* gem install kramdown-asciidoc, see the https://kramdown.gettalong.org/installation.html:[installation guide] for more details
* installation check: `kramdoc --version`

*TODO*: docker ruby image with gem installed to avoid polluting our machines?

=== Migrate sources

Sources (markdown and images files) are stored in the `md` folder of the documentation content repository.

[WARNING]
====
index and releases-notes pages generally contain html elements that cannot be automatically converted. +
There is also a dependency on font-awesome css (`fa-` directives). Font awesome support is available in Asciidoctor

* 1st comment the html part
* Run the migration
* In the converted content, manually convert the html
====


Run the following command to generate the converted files:
[source,bash]
----
find ./ -name "*.md" \
       -type f | xargs -I @@ \
       bash -c 'kramdoc \
               --format=GFM \
               --output=@@.adoc @@';
----

WARNING: test with additional `--wrap=ventilate` option


== Cleanup

Convert custom Bonita tags for notes, warnings, ....

For instance, `:::info Note: for Enterprise, Performance and Efficiency editions only.:::` to
`NOTE: Note: for Enterprise, Performance and Efficiency editions only.`


Note:
[source,bash]
----
sed -i 's/::: info/NOTE:/g' *.adoc
sed -i 's/:::info/NOTE:/g' *.adoc
sed -i 's/::: warning/WARNING:/g' *.adoc
sed -i 's/:::warning/WARNING:/g' *.adoc
sed -i 's/::://g' *.adoc
----

NOTE: for macOS add `''` after the -i option.



== rename files

[source,bash]
----
for f in *.md.adoc; do mv -- "$f" "${f%.md.adoc}.adoc"; done
# Remove remaining md files
rm -rf *.md
----

== move file to the right folder

* Antora layout: move the `md` folder to `modules/ROOT/pages`
* taxonomy: move the page to `modules/ROOT/pages`, otherwise it is considered as a regular pages
* others

== images management

CAUTION: in progress, a definitive solution must be found

[WARNING]
====
Antora expects (at least by default) that images are stored in the `modules/ROOT/assets/images` folder, then they are available
directly in pages as link without having to add a relative path. In the generated site, they are then stored in the `_/_images` folder.

In the original markdown content, the images are accessed through the `images` relative folder. So, if the page content
is not changed, the images must be stored in a `images` folder of the Antora images folder, so in `modules/ROOT/assets/images` (double `images` part in the path).
====

*_Draft_*
