= Netlify redirects configuration

== Configuration files

We use a `netlify.toml` file at the root of the project.

See the https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file[Netlify documentation]
for more details about the how to configure the redirects.

== Testing the redirects

Testing can be done locally thanks to the dev server provided by the https://docs.netlify.com/cli/get-started/[Netlify CLI].

It is able to use the `netlify.toml` used in production and the Netlify `_redirects` file that could be generated by Antora to manage alias. See https://github.com/bonitasoft/bonita-documentation-site/issues/177[#177].

More details about redirects handling in the https://cli.netlify.com/netlify-dev/#redirects[Netlify documentation].



=== Step by step procedure

- Build a preview with the components and versions needed for the test. See xref:../README.adoc#preview-support[README]
- Start the http dev server (see xref:../README.adoc#http-dev-server[README]) 
- In the console, you can see the redirects configuration currently used.
- Any changes in the Netlify redirects configuration is taken into account right away by the server, so the feedback loop is intended to be very short 

[WARNING]
====
*TODO not sure this still applies*


If your redirect returns `200`, the url won't be updated on the preview site if there is no page for the redirect. It returns 200 so you don't go to the 404 page. It is the case for the /latest redirect on the current configuration.  
====




