= Netlify redirects configuration
:icons: font
ifdef::env-github[]
:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Configuration files

We use a `netlify.toml` file at the root of the project.

See the https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file[Netlify documentation]
for more details about the how to configure the redirects.

Antora is configured to generate a Netlify `_redirects` file to manage aliases. The file is generated in `build/site`.
See https://docs.antora.org/antora/2.3/playbook/urls-redirect-facility/#generated-redirect-configuration-for-netlify[Antora] and
https://docs.netlify.com/routing/redirects/[Netlify] documentation for more details.

Be aware of the https://docs.netlify.com/routing/redirects/#rule-processing-order[Netlify rule processing order] for rules
declared in `_redirects` and `netlify.toml`.


== Testing the redirects

Testing can be done locally thanks to the dev server provided by the https://docs.netlify.com/cli/get-started/[Netlify CLI].

It is able to use the `netlify.toml` used in production and

More details about redirects handling in the https://cli.netlify.com/netlify-dev/#redirects[Netlify documentation].


=== Step-by-step procedure

- Build a preview with the components and versions needed for the test. See xref:../README.adoc#preview-support[README]
- Start the http dev server (see xref:../README.adoc#http-dev-server[README])
- In the console, you can see the redirect configuration currently used.
- Any changes in the Netlify redirects configuration is taken into account right away by the server, so the feedback loop is intended to be very short

[WARNING]
====
If your redirect returns `200`, the url won't be updated when you test the redirect. +
To validate it works you have to check the content of the page.
====




