= Documentation Versions
:icons: font
ifdef::env-github[]
:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:url-antora-docs: https://docs.antora.org/antora/3.0

[IMPORTANT]
====
This is a brief overview of all required actions. +
For a complete list of required tasks, see the complete guides (restricted access):

* https://bonitasoft.atlassian.net/wiki/spaces/BS/pages/22504964104/Bonita+Platform+documentation+lifecycle[Bonita Platform documentation lifecycle]
* https://bonitasoft.atlassian.net/wiki/spaces/BS/pages/22503227439/How-to+configure+a+new+documentation+content+component[How-to configure a new documentation content component].
====

NOTE: The following applies mainly to the documentation part of the Bonita Platform, but can be used for any component of the Bonita documentation site with multi-supported versions

== Bonita versions that are documented

For Bonita, the rule is the following one:
[quote]
We document the 4 currently supported Bonita versions, and **the 4 versions before**.


== General how-to for components and versions management

=== How to integrate a new component

To add a new component, you first need to create a GitHub repository which will contain the AsciiDoc sources of this component
(i.e. the documentation content). This repository must be organized according to the {url-antora-docs}/organize-content-files/[Antora recommendations].
You can check existing repositories for working examples.
At minimum, it will contain an `antora.yml` file at its root

You should also add the GitHub workflows (PR preview, push to production, ...). Check existing components for a source of inspiration.

Also update the https://github.com/bonitasoft/bonita-documentation-site/blob/master/scripts/generate-content-for-preview-antora-playbook.js[preview script] to reference the component by its name.


=== How to integrate a new version of an existing component

When we need to add a new version of one component, we need to:

. Create a new branch (in the repository related to the component). Generally, you can start from the branch of the previous version. This lets
.. retrieving all automation workflow (don't forget to update/adapt the configuration as done for a new component)
.. merging change from the previous version to the new version
. Then, you need to add the new version in the https://github.com/bonitasoft/bonita-documentation-site/blob/master/antora-playbook.yml[Antora playbook].
This means adding the new branch to the existing component.
. Finally, update the DocSearch configuration to make this component searchable.


=== How to remove a component version and make an archive available

On new Bonita Platform GA release, an old version must be archived.

. Take the oldest one
. Run the https://github.com/bonitasoft/bonita-documentation-site/actions/workflows/generate-static-doc.yml[archive GitHub Actions]: this creates a new tag on the related component version
. Create a PR targeting the `bonita-doc` archives branch and add the new archive version to the list
. Remove the version from the Antora Playbook
. Remove the version from the DocSearch configuration
. Add a redirect to manage urls of the old version. See how it is done for the versions that are https://github.com/bonitasoft/bonita-documentation-site/blob/master/netlify.toml[already archived].
. in the documentation content repository, remove the GH workflow that triggers the push to production


=== Mark version as 'Out of Support'

NOTE: Please perform all the changes in a dedicated Pull Request (or eventually a single commit in the related branch) for consistency.


Edit the related antora.yml file of the component version, and make the pages non-editable

[source,yml]
----
name: componentName
...
asciidoc:
  attributes:
    # remove the 'Edit this Page' link in all pages
    page-editable: false
    # display a dedicated banner to warn the reader about the out-of-support state
    page-out-of-support: true
----

In the related branch, remove the whole `.github` folder. We don't accept contribution for this version. So remove workflows and the PR template.

As an example, you can check what was done for

* Bonita 7.9: https://github.com/bonitasoft/bonita-doc/commit/7788fcdbc1faff52aa7973a0514c0b707399b963[commit 7788fcd]
* Bonita 7.10: https://github.com/bonitasoft/bonita-doc/pull/1909[PR #1909]

[WARNING]
====
Don't forget to update `../src/propagate_doc_upwards.sh`.

More details <<update-merge-doc-upwards, here>>
====


=== Mark version as 'Next-release'

Edit the related antora.yml file of the component version, make the content not searchable, and adding an information message.

[source,yml]
----
name: componentName
version: 2022.2
prerelease: -alpha
...
asciidoc:
  attributes:
    # Adding an info message on the top of any pages
    page-next-release: true
    # remove search bar for this version (Because the content of next-release is initially not indexed by DocSearch)
    page-hide-search-bar: true
----

Once the DocSearch crawler has indexed the next version, you can display the search bar.


=== Pre-release versions

NOTE: this applies to Alpha, Beta and RC versions

See {url-antora-docs}/component-prerelease/ to know how to

* mark a prerelease version
* display beta/rc additional information in the version
* impact the default version and version ordering


=== GA versions

See {url-antora-docs}/component-prerelease/ to know how to

* remove the prerelease configuration (see above)



=== Propagate documentation upwards

An action is available (and is triggered each night) to propagate documentation changes upwards to avoid you to update all branches.

Example: _We want to merge branches 2021.1 into 2021.2, 2021.2 into 2022.1 ..._

To do it, run `Propagate documentation content upwards` action.

[NOTE]
====
* If an error occurs during the propagation, a Slack notification is sent
* The most frequent cause of error is a merge conflict to be managed manually
====


[[update-merge-doc-upwards]]
==== Update script when adding or removing a version

In `scripts/propagate_doc_upwards.sh`, adapt the `main code` section according to your needs.

[source]
----
merge 2021.1 2022.2
        means
Propagate changes from 2021.1 branches to 2022.2
----
