= Documentation Versions
:icons: font
ifdef::env-github[]
:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:url-antora-docs: https://docs.antora.org/antora/3.0

CAUTION: this is a work in progress

NOTE: the following mainly applies to the Bonita Platform documentation part

== Bonita versions that are documented

For Bonita, the rule is the following one: +
We document the 4 currently supported Bonita versions, and **the 4 versions before**. +

=== Impact on DocSearch

Each time a new version of a documented Bonitasoft project is released, the DocSearch configuration has to be updated:

- The latest version has to be added to the projects to index
- The oldest version should be removed from the projects to index

-> It means that the DocSearch configuration should reflect this behavior.


== Versions lifecycle

NOTE: *this is a work in progress*. TODO link lifecycle actions to the how-to later described in this page

NOTE: this mainly applies to Bonita Platform but all components with multi-supported versions should follow the same rules

GA release (actions to be performed detailed later in this document):

* remove the prerelease configuration (see below)
* update the redirect to make the latest token url go to the new GA version
* archive the oldest version
* mark the 5th version as out of support: On new Bonita Platform GA release, an old version is considered as out of support.


== General how-to for components and versions management

=== How to integrate a new component

[NOTE]
====
This is a brief overview of all required actions. +
For a complete list of required tasks, see the https://bonitasoft.atlassian.net/wiki/spaces/BS/pages/22503227439/How-to+configure+a+new+documentation+content+component[complete guide] (restricted access).
====

To add a new component, you first need to create a GitHub repository which will contain the asciidoc sources of this component
(i.e. the documentation content). This repository must be organized according to the {url-antora-docs}/organize-content-files/[Antora recommendations].
You can check existing repositories for working examples.
At minimum, it will contain an `antora.yml` file at its root

You should also add the GitHub workflows (PR preview, push to production, ...). Check existing components for a source of inspiration.

Also update the https://github.com/bonitasoft/bonita-documentation-site/blob/master/scripts/generate-content-for-preview-antora-playbook.js[preview script] to reference the component by its name.


=== How to integrate a new version of an existing component

When we need to add a new version of one component, we need to:

. Create a new branch (in the repository related to the component). Generally, you can start from the branch of the previous version. This lets
.. retrieving all automation workflow (don't forget to update/adapt the configuration as done for a new component)
.. merging change from the previous version to the new version
. Then, you need to add the new version in the https://github.com/bonitasoft/bonita-documentation-site/blob/master/antora-playbook.yml[Antora playbook].
This means adding the new branch to the existing component.
. Finally, update the <<docsearch-configuration, DocSearch configuration>> to make this component searchable.


=== How to remove a component version and make an archive available

On new Bonita Platform GA release, an old version must be archived.

. Take the oldest one
. Run the archive GitHub Actions: this creates a new tag on the related component version
. Create a PR targeting the bonita-doc archives branch and add the new archive version to the list
. Remove the version from the Antora Playbook
. Remove the version from the DocSearch configuration
. Add a redirect to manage urls of the old version. See how it is done for the versions that are https://github.com/bonitasoft/bonita-documentation-site/blob/master/netlify.toml[already archived].
. in the documentation content repository, remove the GH workflow that triggers the push to production


=== Mark version as 'Out of Support'

NOTE: Please perform all the changes in a dedicated Pull Request (or eventually a single commit in the related branch) for consistency.


Edit the related antora.yml file of the component version, and make the pages non-editable

[source,yml]
----
name: componentName
...
asciidoc:
  attributes:
    # remove the 'Edit this Page' link in all pages
    page-editable: false
    # display a dedicated banner to warn the reader about the out-of-support state
    page-out-of-support: true
----

In the related branch, remove the whole `.github` folder. We don't accept contribution for this version. So remove workflows and the PR template.

As an example, you can check what was done for

* Bonita 7.9: https://github.com/bonitasoft/bonita-doc/commit/7788fcdbc1faff52aa7973a0514c0b707399b963[commit 7788fcd]
* Bonita 7.10: https://github.com/bonitasoft/bonita-doc/pull/1909[PR #1909]

[WARNING]
====
Don't forget to update `../src/propagate_doc_upwards.sh`.

More details <<update-merge-doc-upwards, here>>
====


=== Mark version as 'Next-release'

Edit the related antora.yml file of the component version, make the content not searchable, and adding an information message.

[source,yml]
----
name: componentName
version: 2022.2
prerelease: -alpha
...
asciidoc:
  attributes:
    # Adding an info message on the top of any pages
    page-next-release: true
    # remove search bar for this version (Because the content of next-release is initially not indexed by DocSearch)
    page-hide-search-bar: true
----

Once the DocSearch crawler has indexed the next version, you can display the search bar.

Additional actions

* update the `netlify.toml` file and update the redirect for the `next` version

=== Pre-release versions

apply to beta and RC versions

See {url-antora-docs}/component-prerelease/ to know how to

* mark a prerelease version
* display beta/rc additional information in the version
* impact on default version and version ordering


=== Propagate documentation upwards

An action is available (and is triggered each night) to propagate documentation changes upwards to avoid you to update all branches.

Example: _We want to merge branches 2021.1 into 2021.2, 2021.2 into 2022.1 ..._

To do it, run `Propagate documentation content upwards` action.

[NOTE]
====
* If an error occurs during the propagation, a Slack notification is sending to a channel
* The most common root cause is some conflict to manage manually
====


[[update-merge-doc-upwards]]
==== Update script when adding or removing a version

In `scripts/propagate_doc_upwards.sh`, adapt the `main code` section according to your needs.

[source]
----
merge 2021.1 2022.2
        means
Propagate changes from 2021.1 branches to 2022.2
----
