# WARN: this workflow may be reused in other workflows triggered by a workflow_dispatch or a cron.
name: Compress Images Nightly
on:
  workflow_call:
    inputs:
      pr-title:
        description: 'Title of the Pull Request to create'
        type: string
        default: 'refactor: compress images'
      branch-name:
        description: 'Name of the branch to create'
        type: string
        default: 'refactor/compressed-images'
    secrets:
      github-token:
        description: 'GitHub token for Git operations and API calls'
        required: true

jobs:
  compress:
    name: Compress images on ${{ github.ref_name }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BONITA_CI_PAT }}

      - name: Setup git
        id: git-setup
        uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.BONITA_CI_PAT }}
          compressOnly: true

      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: ${{ inputs.pr-title }} on ${{ github.ref_name }}
          commit-message: 'refactor: compress images'
          branch: ${{ inputs.branch-name }}
          branch-suffix: 'timestamp'
          body: ${{ steps.calibre.outputs.markdown }}
          token: ${{ secrets.BONITA_CI_PAT }}
          author: ${{ steps.git-setup.outputs.name}} <${{ steps.git-setup.outputs.email}}>
          committer: ${{ steps.git-setup.outputs.name}} <${{ steps.git-setup.outputs.email}}>
