# Required until we can use Antora 3.2. When GA will be available, this will be directly done with the build of the preview
name: 'Validate references of PR preview'

on:
  workflow_call: # this allows the workflow to be reused
    inputs:
      build-preview-command:
        description: 'The documentation `build-preview` command to build the preview and validate references. Mandatory when `component-name` is not set. Otherwise, ignored.'
        required: false
        type: string
      component-name:
        description: 'The name of the component to build. If set, the build-preview-command input is ignored'
        required: false
        default: ''
        type: string
      # needed by content repositories (default master) and by the doc-site repository (computed)
      doc-site-branch:
        description: 'The branch of the `bonita-documentation-site` used to build the site preview'
        required: false
        default: 'master'
        type: string
      fail-on-warning:
        description: 'If true, fail the Antora build on warning.'
        required: false
        default: true
        type: boolean

jobs:
  validate_references:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # access to the local actions
        with:
          repository: 'bonitasoft/bonita-documentation-site'
          ref: ${{ inputs.doc-site-branch }}

      - name: Validate PR branch name
        uses: ./.github/actions/validate-pr-branch-name
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Install antora dependencies for xref validation
        shell: bash
        # Antora 3.2 is needed by the Antora Atlas extension
        run: npm install --save-dev antora@3.2.0-alpha.6
      - name: Build Site for a single component
        if: inputs.component-name != ''
        shell: bash
        # '>' Replace newlines with spaces (folded)
        # '-' No newline at end (strip)
        run: >-
          ./build-preview.bash
          --branch "${{ github.head_ref }}"
          --component "${{ inputs.component-name }}"
          --component-repo-url "${{ github.event.pull_request.head.repo.clone_url }}"
          --fail-on-warning "${{ inputs.fail-on-warning }}"
          --fetch-sources true
          --pr "${{ github.event.pull_request.number }}"
      - name: Build Site with custom build-preview command
        if: inputs.component-name == ''
        shell: bash
        # '>' Replace newlines with spaces (folded)
        # '-' No newline at end (strip)
        run: >-
          ${{ inputs.build-preview-command }}
          --fail-on-warning "${{ inputs.fail-on-warning }}"
          --fetch-sources true
          --pr "${{ github.event.pull_request.number }}"
      - name: List the content of the generated site
        uses: ./.github/actions/log-built-site-details
      - name: Archive site
        uses: actions/upload-artifact@v4
        with:
          name: site-reference-validation-pr-${{github.event.pull_request.number}}-${{github.sha}}
          path: build/site

      - uses: actions/checkout@v4 # Ugly hack founds on https://github.com/actions/checkout/issues/692#issuecomment-1502203573
        with:
          repository: 'bonitasoft/bonita-documentation-site'
          ref: ${{ inputs.doc-site-branch }}
