# WARN: this workflow may be reused in other workflows
# * triggered by a pull_request.
# * called with secret: inherit
#
name: Surge build preview

on:
  workflow_call:
    inputs:
      component-name:
        description: 'The name of the component to build. If set, the build-preview-command input is ignored'
        type: string
        required: false
        default: ''
      doc-site-branch:
        description: 'The branch of the `bonita-documentation-site` used to build the site preview'
        type: string
        required: false
        default: 'master'
      build-preview-command:
        type: string
        description: 'The documentation `build-preview` command to build the preview. Mandatory when `component-name` is not set. Otherwise, ignored.'
        required: false
      fail-on-warning:
        type: boolean
        description: 'If true, fail the Antora build on warning. Only applies when the `component-name` input is set.'
        required: false
        default: false
      ignore-errors:
        type: boolean
        description: 'If `true`, ignores Antora error. Only applies when the `component-name` input is set.'
        required: false
        default: true
      

jobs:
  build-pr-preview:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event.action != 'closed'
        with:
          repository: 'bonitasoft/bonita-documentation-site'
          ref: ${{ inputs.doc-site-branch }}
      - name: Validate PR branch name
        uses: ./.github/actions/validate-pr-branch-name
        if: github.event.action != 'closed'
      - uses: bonitasoft/actions/packages/surge-preview-tools@v3
        id: surge-preview-tools
        with:
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}
      - name: Build Setup
        uses: ./.github/actions/build-setup
        if: github.event.action != 'closed'
      - name: Build Site for a single component
        if: github.event.action != 'closed' && inputs.component-name != ''
        shell: bash
        # '>' Replace newlines with spaces (folded)
        # '-' No newline at end (strip)
        run: >-
          ./build-preview.bash
          --branch "${{ github.head_ref }}"
          --component "${{inputs.component-name}}"
          --component-repo-url "${{github.event.pull_request.head.repo.clone_url}}"
          --fetch-sources true
          --fail-on-warning ${{inputs.fail-on-warning}}
          --ignore-errors ${{inputs.ignore-errors}}
          --pr "${{ github.event.pull_request.number }}"
          --site-url "${{ steps.surge-preview-tools.outputs.preview-url }}"
      - name: Build Site with custom build-preview command
        if: github.event.action != 'closed' && inputs.component-name == ''
        shell: bash
        # '>' Replace newlines with spaces (folded)
        # '-' No newline at end (strip)
        run: >-
          ${{ inputs.build-preview-command }}
          --fetch-sources true
          --pr "${{ github.event.pull_request.number }}"
          --site-url "${{ steps.surge-preview-tools.outputs.preview-url }}"
      - name: List the content of the generated site
        if: github.event.action != 'closed'
        uses: ./.github/actions/log-built-site-details
      - name: Upload site preview
        if: github.event.action != 'closed'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build/site
        
