# WARN: this workflow may be reused in other workflows
# * triggered by a pull_request_target (to work with fork repository). This workflow doesn't do any unsecure action regarding the pull_request_target context.
# * called with secret: inherit
# * with:
#    permissions:
#     pull-requests: write
name: Comments PR with changes list

on:
  workflow_call: # this allows the workflow to be reused
    inputs:
      component-name:
        type: string
        description: "The name of the component to build."
        required: false
        default: "bonita"
      pattern:
        type: string
        description: ""
        required: false
        default: "modules/**/pages/**/*.adoc"
      # needed by content repositories (default master) and by the doc-site repository (computed)
      doc-site-branch:
        type: string
        description: "The branch of the `bonita-documentation-site` used to download js files"
        required: false
        default: "master"

jobs:
  # IMPORTANT: the job id must be the same as in "_reusable_surge-deploy-preview.yml" as the surge-preview-tools action uses it to generate the preview URL (current limitation of v3.2.0)
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: bonitasoft/actions/packages/surge-preview-tools@v3
        id: surge-preview-tools
        with:
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}
      - uses: actions/checkout@v4 # access to the local action
        with:
          repository: 'bonitasoft/bonita-documentation-site'
          ref: ${{ inputs.doc-site-branch }}
          path: ./.github/actions/bds-action
      - name: Publish comments
        uses: ./.github/actions/bds-action/comment-pr-with-links
        with:
          site-url: ${{ steps.surge-preview-tools.outputs.preview-url }}
          pattern: ${{ inputs.pattern }}
          component-name: ${{ inputs.component-name }}
          doc-site-branch : ${{ inputs.doc-site-branch }}
