# WARN: this workflow may be reused in other workflows triggered by a "workflow_run" event.

# Permissions required by this workflow that MUST be set in the calling workflow as this workflow can only downgrade permissions (https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow)
# pull-requests: write / "afc163/surge-preview@v1" write PR comments when the Surge deployment is done
name: Surge deploy preview

on:
  workflow_call:

jobs:
  # MUST be unique across all surge preview deployments for a repository as the job id is used in the deployment URL
  # IMPORTANT: the job id must be the same as in "_reusable_pr-comment-list-changes.yml" as the surge-preview-tools action uses it to generate the preview URL (current limitation of v3.2.0)
  # IMPORTANT: the logic is duplicated in the `surge-deploy-pr-preview-test.yml` workflow. Keep both definitions in sync.
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: site  # must be kept in sync with the artifact name downloaded in the build stage
          path: build/site
      - uses: bonitasoft/actions/packages/surge-preview-tools@fix/surge_deploy
        id: surge-preview-tools
        with:
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}
          github-token: ${{ secrets.BONITA_CI_PAT }} # Avoid rate limiting produced with default GITHUB_TOKEN
      - name: Publish preview
        uses: afc163/surge-preview@v1
        if: steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
        with:
          surge_token: ${{ secrets.SURGE_TOKEN_DOC }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: build/site
          failOnError: true
          teardown: true
          build: echo "site already built"
