# Validate references of PR preview, until we can use Antora 3.2. When GA will be available, this will be directly done with the build of the preview
name: PR Build documentation site
on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/actions/build-pr-site/**/*'
      - '.github/workflows/build-pr-site.yml'
      - '.nvmrc'
      - 'resources/**/*'
      - 'antora-playbook.yml'
      - 'build-preview.bash'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build_site:
    uses: ./.github/workflows/_reusable_surge-build-preview.yml
    with:
      doc-site-branch: ${{ github.head_ref }}
      # '>' Replace newlines with spaces (folded)
      # '-' No newline at end (strip)
      build-preview-command: >-
        ./build-preview.bash
        --single-branch-per-repo
