name: Commit Message format check 

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-22.04
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-body-regex: '(.*\n*)+(.*)'
