name: Comments PR with useful links

on:
  pull_request:   

jobs:
  site:
    permissions:
      pull-requests: write # write PR comments
    uses: ./.github/workflows/_reusable_pr-comments.yml
    secrets: inherit
