name: Compress Images
on:
  pull_request:
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '.github/workflows/compress-images.yml'
      - '.github/workflows/_reusable_compress-images.yml'

jobs:
  compress:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/_reusable_compress-images.yml
