name: Compress Images
on:
  pull_request:
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '.github/workflows/compress-images.yml'
      - '.github/workflows/_reusable_compress-images.yml'

permissions:
  pull-requests: write
  contents: write

jobs:
  compress:
    permissions:
      pull-requests: write # "afc163/surge-preview@v1" write PR comments when the PR is deployed
    uses: ./.github/workflows/_reusable_compress-images.yml
    secrets: inherit