name: Generate static version
on:
  workflow_dispatch:
    inputs:
      newRelease:
        description: If true, create a new GitHub Release and attach the archive as a release asset (only work for bonita-doc)
        default: true
        required: true
      component:
        description: Name of the component name to generate documentation
        # Here we let choose the component name but, currently, the repository where the GH release is created is hard-coded to bonita-doc
        default: bonita
        required: true
      branch:
        description: Branch of the documentation used to generate the archive. For versioned component, the name of the branch matches the version of the documentation.
        required: true
      title:
        description: It is used in the header and tabs of all generated pages. It also used to fill the body of the GitHub release.
        default: Bonita <version> - Archive
        required: true
jobs:
  generate_static_doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Generate static documentation
        # '>' Replace newlines with spaces (folded)
        # '-' No newline at end (strip)
        run: >-
          ./build-preview.bash
          --branch "${{ github.event.inputs.branch }}"
          --component "${{ github.event.inputs.component }}"
          --fetch-sources true
          --hide-edit-page-links true
          --hide-navbar-components-list true
          --ignore-errors true
          --site-title "${{ github.event.inputs.title }}"
          --site-url DISABLED
          --type local
      - name: Zip docs
        if: (github.event.inputs.newRelease == 'true')
        run: |
          echo "timeStamp=$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV
          cd build/site/
          zip -q -r ../documentation-"${{ github.event.inputs.component }}"-"${{ github.event.inputs.branch }}".zip .
      - uses: ncipollo/release-action@v1
        if: (github.event.inputs.newRelease == 'true')
        with:
          owner: bonitasoft
          repo: bonita-doc
          commit: ${{github.event.inputs.branch}}
          tag: ${{ github.event.inputs.branch }}-${{ env.timeStamp}}
          artifacts: "build/documentation-*"
          body: ${{ github.event.inputs.title }}
          token: ${{ secrets.GH_PAT_TOKEN }}
      - name: archives-artefact
        if: (github.event.inputs.newRelease != 'true')
        uses: actions/upload-artifact@v3
        with:
          name: documentation-${{ github.event.inputs.component }}-${{ github.event.inputs.branch }}
          path: build/site
