name: Generate static version
on:
  workflow_dispatch:
    inputs:
      newRelease:
        description: True to create a new github Release
        default: true
        required: true
      component:
        description: Component name to generate documentation
        default: bonita
        required: true
      branch:
        description: Branch version to generate
        required: true
      title:
        description: Title to put in the header and tab
        default: Bonita BPM - Archived
        required: true
jobs:
  generate_static_doc:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Generate static documentation
        run: |
            ./build-preview.bash --branch "${{ github.event.inputs.branch }}" --component "${{ github.event.inputs.component }}" \
                                 --site-title "${{ github.event.inputs.title }}" \
                                 --type local --site-url DISABLED --hide-edit-page-links true --hide-navbar-components-list true
      - name: Zip docs
        if: (github.event.inputs.newRelease == 'true')
        run: |
          echo "timeStamp=$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV
          cd build/site/
          zip -q -r ../documentation-"${{ github.event.inputs.component }}"-"${{ github.event.inputs.branch }}".zip .
      - uses: ncipollo/release-action@v1
        if: (github.event.inputs.newRelease == 'true')
        with:
          owner: bonitasoft
          repo: bonita-doc
          commit: ${{github.event.inputs.branch}}
          tag: ${{ github.event.inputs.branch }}-${{ env.timeStamp}}
          artifacts: "build/documentation-*"
          body: ${{ github.event.inputs.title }}
          token: ${{ secrets.GH_PAT_TOKEN }}
      - name: archives-artefact
        if: (github.event.inputs.newRelease != 'true')
        uses: actions/upload-artifact@v2
        with:
          name: documentation-${{ github.event.inputs.component }}-${{ github.event.inputs.branch }}
          path: build/site
