name: Contribution checks on test data

on:
# TODO restore PR target
  pull_request:
    paths:
      - '.github/workflows/_reusable_pr-antora-content-guidelines-checker.yml'
      - '.github/workflows/pr-antora-checker-test.yml'
      - 'test/documentation-content/**/*'

jobs:
  check_antora_content_guidelines:
    permissions:
      pull-requests: write # "pr-antora-content-guidelines-checker" write PR comments when the PR doesn't match the "Guidelines"
    # TODO restore master
    uses: bonitasoft/bonita-documentation-site/.github/workflows/_reusable_pr-antora-content-guidelines-checker.yml@fix/antora-content-check-filter-files-from-state
        with:
