name: Comments PR with changes list

on:
  pull_request_target:
    paths:
      - '.github/actions/comment-pr-with-links/**/*'
      - '.github/workflows/_reusable_pr-comment-list-changes'
      - '.github/workflows/pr-comment-list-changes.yml'

jobs:
  site:
    permissions:
      pull-requests: write # write PR comments
    uses: ./.github/workflows/_reusable_pr-comment-list-changes.yml
    secrets: inherit
