name: Propagate documentation
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'If true, run the merge locally but do not push to remote'
        required: false
        default: 'false'
      slack-notifications:
        description: 'If true, send slack notifications when errors occur'
        required: false
        default: 'true'

jobs:
  propagate-doc-upwards:
    runs-on: ubuntu-20.04
    strategy:
      # we want to run the full build on all os: don't cancel running jobs even if one fails
      fail-fast: false
      matrix:
        repo: [bonita-doc]
    steps:
      - name: Checkout bonita-documentation-site
        uses: actions/checkout@v3
        with:
          path: ./bonita-documentation-site
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v3
        with:
          repository: bonitasoft/bonita-doc
          token: ${{ secrets.GH_PAT_TOKEN }} # Dedicated token to have 'write permission' (we later push to this repository)
          path: ./${{ matrix.repo }}
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: '0'

      - name: Run propagate doc upwards
        env:
          NO_PUSH: ${{ github.event.inputs.dry-run }}
          REPO_NAME: ${{ matrix.repo }}
        run: |
          cd ./${{ matrix.repo }}
          
          # configure committer information
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
                   
          echo "########################################"
          echo "Performing the doc propagation"
          echo "########################################"
          ./.././bonita-documentation-site/scripts/propagate_doc_upwards.bash

      - name: Send message to Slack channel
        if: failure() && $ github.event.inputs.slack-notifications == 'true'
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: 'CCQGMR4ES'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":fire:  Propagating documentation upwards failed for repository **${{matrix.repo}}**. \n \n  @channel *We need someone* ! \n  - Add a :fire_extinguisher:if you take the action to resolve the conflicts (only one person is required) \n - Add a :sweat_drops: when it’s done (and eventually a :party_parrot: )"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "More details about the error <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true| here> \n More details on solving the conflicts locally <https://bonitasoft.atlassian.net/wiki/spaces/BS/pages/1181483014/Bonita+documentation+site+content+update#Bonita| there>"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "_Cela semble toujours impossible jusqu’à ce qu’on le fasse._\n _Mandela_"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
