name: Surge build - preview site

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/actions/build-setup/**/*'
      - '.github/actions/comment-pr-with-links/**/*'
      - '.github/workflows/_reusable_surge-build-preview.yml'
      - '.github/workflows/surge-build-preview-site.yml'
      - '.nvmrc'
      - 'resources/**/*'
      - 'antora-playbook.yml'
      - 'build-preview.bash'
      - 'package.json'
      - 'package-lock.json'

# TMP updated to trigger the workflow
jobs:
  build-preview-site:
    uses: ./.github/workflows/_reusable_surge-build-preview.yml
    secrets: inherit
    with:
      doc-site-branch: ${{ github.head_ref }}
      build-preview-command: >-
        ./build-preview.bash
        --ignore-errors true
        --single-branch-per-repo
