name: List surge.sh domains
on:
# TODO change to workflow_dispatch once it is tested
  pull_request:

jobs:
  list_deployments:
    runs-on: ubuntu-22.04
    steps:
      - name: List deployments
        run: |
          npx surge --token ${{ secrets.SURGE_TOKEN_DOC }} list
