name: Deploy Surge preview

on:
  workflow_run:
    workflows:
      - "Surge build - preview site"
      - "Surge build - preview test"
    types:
      - completed

jobs:
  # TODO we cannot have a single workflow here
  # the surge url is based on the job id, so if we want 2 deployments, we need 2 jobs, so in this case, one workflow per build workflow
  deploy_surge_preview:
    permissions:
      pull-requests: write # "afc163/surge-preview@v1" write PR comments when the PR is deployed
    uses: ./.github/workflows/_reusable_surge-deploy-preview.yml
    secrets: inherit
