name: Surge build - preview test

on:
  pull_request:

jobs:
  build-preview-test:
    uses: ./.github/workflows/_reusable_surge-build-preview.yml
    secrets: inherit
    with:
      doc-site-branch: ${{ github.head_ref }}
      # here we check the
      #   - detailed logs of the Antora extensions
      #   - DocSearch integration
      build-preview-command: >-
        ./build-preview.bash
        --fail-on-warning true
        --force-display-search-bar
        --log-level debug
        --use-test-sources
      
      