name: Teardown inactive site

on:
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch:

jobs:
  teardown_inactive_deployement:
    runs-on: ubuntu-20.04
    steps:
      - name: Teardown surge deployement inactive than more 1 month
        uses: adrianjost/actions-surge.sh-teardown@v1.0.3
        with:
          regex: '[1-9]+ month.? ago'
        env:
          SURGE_LOGIN: "hudson.mailer@bonitasoft.com"
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN_DOC }}