name: Teardown inactive site

on:
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch:

jobs:
  teardown_inactive_deployement:
    runs-on: ubuntu-22.04
    steps:
      - name: Teardown surge deployement inactive than more 1 month
        uses: adrianjost/actions-surge.sh-teardown@v1.0.3
        with:
          regex: '[1-9]+ month.? ago'
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN_DOC }}
      - name: Send message to Slack channel
        if: failure()
        uses: bonitasoft/notify-slack-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          channel-id: ${{ vars.RD_PLATFORM_SLACK_CHANNEL_ID }}
          message: |
            :red_circle: The teardown of inactive documentation preview sites has failed!

            @channel *We need someone* !
